### PR TITLE
Updated names and comments of connections in FanCoilUnit folder

### PR DESCRIPTION
**Pull request by junkewang001**

### CODE REVIEW

**Comment by karthikeyad-pnnl** [comment]
@junkewang001 The validation models are failing after I merged these changes. Can you confirm it on your end? Also, lets try to set up the unit tests today

**Comment by junkewang001** [comment]
I have updated the names of the connections in the validation models accordingly. All the models work successfully in my end now. Please feel free to help do the unit. Thanks!

**Comment by karthikeyad-pnnl** [comment]
@junkewang001 Can you please also propagate the naming changes to the validation scripts? There are missing variables in the validation plots

**Comment by junkewang001** [comment]
Have propagated the naming changes to the validation scripts and submitted a new PR.

**Pull request merged**
